### PR TITLE
Test --no-default-features as well

### LINKED ISSUE #30: Test the no_std mode
It would be great to add to .travis.yml an additional test run which does `cargo test --no-default-features` (turning off the `std` feature) on stable. The 4 existing test runs should still use std.

Not sure how to do this, but I'm sure its possible if someone reads the Travis docs. :)

### LINKED ISSUE #114: examples/bail_ensure fails no_std test
```
$ cargo test --no-default-features
   Compiling failure v0.1.1 (file:///home/travis/build/withoutboats/failure)
error[E0432]: unresolved import `failure::Error`
 --> examples/bail_ensure.rs:4:5
  |
4 | use failure::Error;
  |     ^^^^^^^^^^^^^^ no `Error` in the root
error: cannot find macro `bail!` in this scope
 --> examples/bail_ensure.rs:8:5
  |
8 |     bail!("ruh {}", "roh");
  |     ^^^^
error: cannot find macro `ensure!` in this scope
  --> examples/bail_ensure.rs:12:5
   |
12 |     ensure!(true, "true is false");
   |     ^^^^^^
error: cannot find macro `ensure!` in this scope
  --> examples/bail_ensure.rs:13:5
   |
13 |     ensure!(false, "false is false");
   |     ^^^^^^
error: aborting due to 4 previous errors
error: Could not compile `failure`.
warning: build failed, waiting for other jobs to finish...
error: build failed
The command "cargo test --no-default-features" exited with 101.
```

Somehow this example needs to only be tested with the `std` feature. I don't know how to do this at this time.

Discovered in #113.

### PR DESCRIPTION
**Pull request by CAD97**
Closes #30 
Closes #114 

This sets travis's test script to do both `cargo test` and `cargo test --no-default-features`.

Note: The matrix is still size 4 (compile on 1.18.0, stable, beta, and nightly).
This just means that each member of the matrix does (effectively) `cargo test && cargo test --no-default-features` instead of just `cargo test`.

The `--no-default-features` build only recompiles failure and not any of the dependencies, so it shouldn't break the cache.

### CODE REVIEW

**Comment by CAD97** [comment]
See https://travis-ci.org/withoutboats/failure/jobs/317229211 for an example run (stable).

**Comment by CAD97** [comment]
Workaround in 2b50710 is not ideal as it only tests `--lib` and misses `--doc`, `--bins`, `--examples`, `--tests`, and `--benches` targets in the test harness. We want to miss `--examples` currently to avoid testing the example(s) which do(es)n't work in no_std.

Interestingly, apparently no tests are present in the no_std build that I could find, so the harm is minimal. I still would recommend reverting 2b50710 once #114 is addressed properly.

**Comment by withoutboats** [comment]
> We want to miss --examples currently to avoid testing the example(s) which do(es)n't work in no_std.

The example should probably be `cfg`d to compile as nothing in no_std mode, right?

**Comment by CAD97** [comment]
And, when I checked the documentation once more, I found how to do it: [The `required-features` field](http://doc.crates.io/manifest.html#the-required-features-field-optional). Missed that the first time.

**Comment by CAD97** [comment]
Rebased on top of #121 so that tests can pass

**Comment by CAD97** [comment]
Rebased on top of fixed #121 so that tests actually pass

**Comment by withoutboats** [comment]
Awesome, thanks for doing this!
